<?php

$sLangName = "Deutsch";

$aLang = [
    'charset' => 'UTF-8',
    'tbclattribute_value' => 'Werte',
    'DETAILS_Attributes_TYPE' => 'Eingabetyp',
    'ARTICLE_ATTRIBUTE_SAVE' => 'Speichern',
    'ARTICLE_ATTRIBUTE_SELECTONEATTR' => 'Attribut wählen:',
    'ARTICLE_ATTRIBUTE_NOATTRIBUTE' => 'Verfügbare Attribute',
    'ARTICLE_ATTRIBUTE_ITEMSATTRIBUTE' => 'Zugeordnete Attribute',
    'YES' => 'Ja',
    'NO' => 'Nein',
    'GENERAL_AJAX_SORT_OXVALUE' => 'Wert',
    'GENERAL_AJAX_SORT_OXTYPE' => 'Typ',
    'GENERAL_AJAX_SORT_OXATTRVALUEID' => 'Wert-ID',
    'ATTR_TYPE_TEXT' => 'Text',
    'ATTR_TYPE_SELECT' => 'Auswahl',
    'ATTR_TYPE_MULTISELECT' => 'Mehrfachauswahl',
    'ATTR_TYPE_BOOL' => 'Ja / Nein',
    'ATTR_TYPE_DATE' => 'Datum',
    'ATTR_TYPE_DATETIME' => 'Datum & Uhrzeit',
    'ATTR_TYPE_PRICE' => 'Preis',
    'ATTR_TYPE_COLOR' => 'Farbe',
    'ATTR_TYPE_IMAGE' => 'Bild',
    'ATTR_TYPE_TEXT_SWATCH' => 'Text-Muster',
    'ATTR_TYPE_VISUAL_SWATCH' => 'Visuelles Muster',
    'ATTR_TYPE_TEXT_INFO' => 'ist ein Text-Attribut. Vordefinierte Werte werden für Textattribute nicht verwendet.',
    'ATTR_TYPE_BOOL_INFO' => 'ist ein Ja/Nein-Attribut. Werte werden pro Produktzuordnung gesetzt.',
    'ATTR_TYPE_DATE_INFO' => 'ist ein Datum-Attribut. Werte werden pro Produktzuordnung eingegeben.',
    'ATTR_TYPE_PRICE_INFO' => 'ist ein Preis-Attribut. Werte werden pro Produktzuordnung eingegeben.',
    'ATTR_TYPE_UNKNOWN_INFO' => 'Dieser Attributtyp unterstützt keine verwalteten Werte.',
    'ATTR_VALUES_MANAGE' => 'Werte verwalten für',
    'ATTR_VALUES_SORT' => 'Sortierung',
    'ATTR_VALUES_VALUE' => 'Wert',
    'ATTR_VALUES_COLOR' => 'Farbe (Hex)',
    'ATTR_VALUES_IMAGE' => 'Bild',
    'ATTR_VALUES_ADD_NEW' => 'Neu hinzufügen',
    'ATTR_VALUES_NEW_VALUE' => 'Neuer Wert',
    'ATTR_VALUES_ADD' => 'Hinzufügen',
    'ATTR_TRANSLATION_WARNING' => 'Wert wurde für alle Sprachen mit dem gleichen Text erstellt. Bitte übersetzen Sie für andere Sprachen.',
];
