<?php

$sLangName = "English";

$aLang = [
    'charset' => 'UTF-8',
    'tbclattribute_value' => 'Values',
    'DETAILS_Attributes_TYPE' => 'Input Type',
    'ARTICLE_ATTRIBUTE_SAVE' => 'Save',
    'ARTICLE_ATTRIBUTE_SELECTONEATTR' => 'Select Attribute:',
    'ARTICLE_ATTRIBUTE_NOATTRIBUTE' => 'Available Attributes',
    'ARTICLE_ATTRIBUTE_ITEMSATTRIBUTE' => 'Assigned Attributes',
    'YES' => 'Yes',
    'NO' => 'No',
    'GENERAL_AJAX_SORT_OXVALUE' => 'Value',
    'GENERAL_AJAX_SORT_OXTYPE' => 'Type',
    'GENERAL_AJAX_SORT_OXATTRVALUEID' => 'Value ID',
    'ATTR_TYPE_TEXT' => 'Text',
    'ATTR_TYPE_SELECT' => 'Selection',
    'ATTR_TYPE_MULTISELECT' => 'Multi-Select',
    'ATTR_TYPE_BOOL' => 'Yes / No',
    'ATTR_TYPE_DATE' => 'Date',
    'ATTR_TYPE_DATETIME' => 'Date & Time',
    'ATTR_TYPE_PRICE' => 'Price',
    'ATTR_TYPE_COLOR' => 'Color',
    'ATTR_TYPE_IMAGE' => 'Image',
    'ATTR_TYPE_TEXT_SWATCH' => 'Text Swatch',
    'ATTR_TYPE_VISUAL_SWATCH' => 'Visual Swatch',
    'ATTR_TYPE_TEXT_INFO' => 'is a Text attribute. Predefined values are not used for text attributes.',
    'ATTR_TYPE_BOOL_INFO' => 'is a Yes/No attribute. Values are set per product assignment.',
    'ATTR_TYPE_DATE_INFO' => 'is a Date attribute. Values are entered per product assignment.',
    'ATTR_TYPE_PRICE_INFO' => 'is a Price attribute. Values are entered per product assignment.',
    'ATTR_TYPE_UNKNOWN_INFO' => 'This attribute type does not support managed values.',
    'ATTR_VALUES_MANAGE' => 'Manage Values for',
    'ATTR_VALUES_SORT' => 'Sort',
    'ATTR_VALUES_VALUE' => 'Value',
    'ATTR_VALUES_COLOR' => 'Color (Hex)',
    'ATTR_VALUES_IMAGE' => 'Image',
    'ATTR_VALUES_ADD_NEW' => 'Add New',
    'ATTR_VALUES_NEW_VALUE' => 'New Value',
    'ATTR_VALUES_ADD' => 'Add',
    'ATTR_TRANSLATION_WARNING' => 'Value created for all languages with the same text. Please translate for other languages.',
];
